apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hub
    path: hook/hub.yaml
  # - target:
  #     group: apps
  #     version: v1
  #     kind: Deployment
  #     name: hub
  #   path: hook/hub.yaml
