name: "kubernetes-deployment"
description: "kubernetes rolling update management"
inputs:
  json_key:
    description: "service account key json encode in base64"
    required: true
  cluster:
    description: "cluster name"
    required: true
  image:
    description: "docker image <docker_image>:<tag>"
    require: true
  deployment:
    description: "deployment on k8s"
    require: true
  container:
    description: "Container name on the deployment"
output:
  current:
    decscription: "Current tag after rolling update"
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.json_key }}
    - ${{ inputs.cluster }}
    - ${{ inputs.image }}
    - ${{ inputs.deployment }}
    - ${{ inputs.container }}
